# ===================================
#  WakaController | Workflow | Productor |  Behavior Config
# ===================================


modelClass: Waka\Docser\Models\CategoryDoc
backendUrl: waka/docser/categorydocs

workflow: false 


controllerConfig:
    breadcrumb:
        inSettings: true 
        title: waka.docser::lang.models.categorydoc.label
        rows: 
            preIndex: 
                label: waka.docser::lang.controllers.appdocs.label
                url:  waka/docser/appdocs 
            index: 
                label: waka.docser::lang.controllers.categorydocs.label
                url: waka/docser/categorydocs 
    index:
        base:
            create: 
                show: true
                permissions: [waka.docser.*]
            reorder: 
                show: true  
                permissions: [waka.docser.*]
            delete: 
                show: true
                permissions: [waka.docser.*]
        partials:
            index_btn:
                url: $/waka/docser/controllers/categorydocs/_index_btn.php
    update:
        # partials:
        #     update_btn:
        #         url: $/waka/docser/controllers/categorydocs/_update_btn.php

reorder:
    title: waka.wutils::lang.global.reorder