# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.docser::lang.controllers.appdocs.label

# Model Form Field configuration
form: $/waka/docser/models/appdoc/fields.yaml

# Model Class name
modelClass: Waka\Docser\Models\Appdoc

# Default redirect location
defaultRedirect: waka/docser/appdocs

# Create page
create:
    title: backend::lang.form.create_title
    redirect: waka/docser/appdocs/update/:id
    redirectClose: waka/docser/appdocs

# Update page
update:
    title: backend::lang.form.update_title
    redirect: waka/docser/appdocs
    redirectClose: waka/docser/appdocs

# Preview page
preview:
    title: backend::lang.form.preview_title
